### PR TITLE
Open customisable window rather than dialog window

### PR DESCRIPTION
**Pull request by DayBr3ak**
In regard to the issue #20 

User can specify an html page as a custom alert.

### CODE REVIEW

**Comment by G07cha** [comment]
Hi, @DayBr3ak 
First of all, thanks for your huge contribution. It looks good but I personally think that user-defined templates is excess functionality. We could have just a simple one.

**Comment by petems** [comment]
@DayBr3ak Hey, bit of confusion here, I offered the bounty on my fork of this module, so the issue was for that: https://github.com/petems/time-to-stretch/issues/1

If you re-open your PR against my repo, everything's good 👍

**Comment by G07cha** [comment]
I'm glad that there will be no wasted code, @petems to speed up things you could merge this branch by yourself in "time-to-stretch" repo.

**Comment by DayBr3ak** [comment]
My bad

**Pull request closed without merging**
