### PR TITLE
upgrade electron to v7

### PR DESCRIPTION
**Pull request by gianpaj**

### CODE REVIEW

**Comment by G07cha** [comment]
Looks good overall, great work @gianpaj!
Two points that I would like to address before merging this:

1. You've used prettier with default configuration which uses double quotes(`"`) but [current ESLint config](https://github.com/gianpaj/pomodoro-1/blob/feature/upgrade-electron/.eslintrc.js#L232-L235) enforces single quotes(`'`) so there is a bit of a mismatch, maybe we can remove rule from ESLint config and incorporate Prettier in there instead using [prettier-eslint](https://github.com/prettier/prettier-eslint)?
2. CI pipeline and build in general is broken since with newer versions `electorn-build` should be used instead of `build`, do you mind replacing it here: https://github.com/gianpaj/pomodoro-1/blob/feature/upgrade-electron/package.json#L18-L19 ?

I hope it's not too much, again, really appreciate the work you've done! 🚀

**Comment by G07cha** [comment]
Awesome, thanks for getting back! There is still a build failing for some reason but I will look into it separately. Thanks for your contribution!

**Comment by gianpaj** [comment]
cool. no problem.

Re. issue: I'm not an expert in electron what so ever but the macOS build worked on my mac 🍎

**Comment by G07cha** [comment]
Indeed, it also builds on mine, I've discovered it was because of old XCode being used in the pipeline

**Pull request merged**
